/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ExcelDefinition } from "./declarations/ExcelDefintion";
export { ExcelDefinition } from "./declarations/ExcelDefintion";
export namespace Components {
    interface ImportExportDefinition {
        "culture": 'zh' | 'en';
        "definition": ExcelDefinition;
    }
    interface ImportExportStudio {
        "culture": 'zh' | 'en';
        "data": any[];
        "definition": ExcelDefinition;
    }
    interface ImportExportTable {
        "data": any[];
        "definition": ExcelDefinition;
    }
}
declare global {
    interface HTMLImportExportDefinitionElement extends Components.ImportExportDefinition, HTMLStencilElement {
    }
    var HTMLImportExportDefinitionElement: {
        prototype: HTMLImportExportDefinitionElement;
        new (): HTMLImportExportDefinitionElement;
    };
    interface HTMLImportExportStudioElement extends Components.ImportExportStudio, HTMLStencilElement {
    }
    var HTMLImportExportStudioElement: {
        prototype: HTMLImportExportStudioElement;
        new (): HTMLImportExportStudioElement;
    };
    interface HTMLImportExportTableElement extends Components.ImportExportTable, HTMLStencilElement {
    }
    var HTMLImportExportTableElement: {
        prototype: HTMLImportExportTableElement;
        new (): HTMLImportExportTableElement;
    };
    interface HTMLElementTagNameMap {
        "import-export-definition": HTMLImportExportDefinitionElement;
        "import-export-studio": HTMLImportExportStudioElement;
        "import-export-table": HTMLImportExportTableElement;
    }
}
declare namespace LocalJSX {
    interface ImportExportDefinition {
        "culture"?: 'zh' | 'en';
        "definition"?: ExcelDefinition;
    }
    interface ImportExportStudio {
        "culture"?: 'zh' | 'en';
        "data"?: any[];
        "definition"?: ExcelDefinition;
    }
    interface ImportExportTable {
        "data"?: any[];
        "definition"?: ExcelDefinition;
    }
    interface IntrinsicElements {
        "import-export-definition": ImportExportDefinition;
        "import-export-studio": ImportExportStudio;
        "import-export-table": ImportExportTable;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "import-export-definition": LocalJSX.ImportExportDefinition & JSXBase.HTMLAttributes<HTMLImportExportDefinitionElement>;
            "import-export-studio": LocalJSX.ImportExportStudio & JSXBase.HTMLAttributes<HTMLImportExportStudioElement>;
            "import-export-table": LocalJSX.ImportExportTable & JSXBase.HTMLAttributes<HTMLImportExportTableElement>;
        }
    }
}
