[package]
name = "imexport-wasm"
version = "0.0.1"
edition = "2021"
description = "Rust WebAssembly for import/export Excel files"
repository = "https://github.com/gui-xie/import-export"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
calamine = "0.25"
wasm-bindgen = "0.2"
console_error_panic_hook = {version = "0.1.7", optional = true }
rust_xlsxwriter = {version="0.75.0", features = ["wasm"] }

[dev-dependencies]
wasm-bindgen-test = "0.3"

