[package]
name = "imexport-wasm"
version = "0.0.1"
edition = "2021"
description = "Rust WebAssembly for import/export Excel files"
repository = "https://github.com/gui-xie/import-export"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[profile.release]
lto = true
opt-level = 's'

[dependencies]
wasm-bindgen = "0.2"
console_error_panic_hook = {version = "0.1.7", optional = true }
rust_xlsxwriter = {version="0.77", features = ["wasm", "default"] }
chrono = "0.4.39"
js-sys = "0.3.77"
futures = "0.3.31"
wasm-bindgen-futures = "0.4.50"
calamine = {version = "0.26.1", features = ["picture"] }

[dev-dependencies]
insta = "1.16.0"
tokio = { version = "1", features = ["rt", "macros"] }

[package.metadata.wasm-pack.profile.dev.wasm-bindgen]
debug-js-glue = true
demangle-name-section = true
dwarf-debug-info = false
omit-default-module-path = false

[package.metadata.wasm-pack.profile.profiling]
wasm-opt = ['-O']

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[package.metadata.wasm-pack.profile.profiling.wasm-bindgen]
debug-js-glue = false
demangle-name-section = true
dwarf-debug-info = false
omit-default-module-path = false
